---
baseURL: ''
languageCode: 'en-us'
title: 'Samer Bahri'
theme: hugo-profile

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blog
      weight: 1
    # - identifier: projects
    #   name: Projects
    #   title: Projects
    #   url: /projects
    #   weight: 2
    - identifier: resources
      name: Resources
      title: Resources
      url: /resources
      weight: 3
    # - identifier: about
    #   name: About
    #   title: About Me
    #   url: /about
    #   weight: 4

params:
  title: "Samer Bahri"
  description: DevOps Engineer
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: true

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Samer Bahri" # Brand name for the brand | default is the title variable
    disableSearch: true
    # searchPlaceholder: "Search"
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Samer Bahri."
    subtitle: "I build automations and systems"
    content: "A passionate DevOps engineer. I tend to make use of modern cloud technologies to build automations that run smoothly, feel seamless, and function correctly."
    image: "/images/me.png"
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "#"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/samerbahri98
        - icon: fab fa-twitter
          url: https://twitter.com/SamerBahri5
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/samerbahri

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/me.png"
    content: |-
      I am a DevOps Engineer with a passion for cloud technologies. I have a background in computer science and software engineering, and I have a strong interest in the intersection of open source and enterprise softwares and systems. I am currently working as an experienced DevOps engineer at [Ericsson](https://www.ericsson.com/en) in Budapest.

      I am currently working on a robust and secure cloud native data storage solution that will be used to help comapnies provide the best 5G services way to their customers.
    skills:
      enable: true
      title: "Here are a few technologies I am very familiar with:"
      items:
        - "Docker"
        - "Kubernetes"
        - "Terraform"
        - "Ansible"
        - "Python"
        - "Go"
        - "Typescript"
        - "Jenkins"
        - "Amazon Web Services"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Experienced Developer"
        company: "Ericsson"
        companyUrl: "https://www.ericsson.com/en"
        date: "March 2023 - present"
        featuredLink:
          enable: false
        info:
          enable: false
        content: "I am currently working as an experienced DevOps engineer at [Ericsson](https://www.ericsson.com/en) in Budapest. I am currently working on a robust and secure cloud native data storage solution that will be used to help comapnies provide the best 5G services way to their customers."

      - job: "Developer Intern"
        company: "Continental AG"
        companyUrl: "https://www.continental.com/de/"
        date: "Mar 2022 - Feb 2023"
        featuredLink:
          enable: false
        info:
          enable: false
        content: |
          I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

          - Lead backend developer for a product.
          - Created a frontend design for a product.

  # Education
  education:
    enable: true
    index: false
    items:
      - title: "BSc in Computer Science"
        school:
          name: "Budapest University of Technology and Economics"
          url: "https://www.bme.hu/"
        date: "2019 - 2023"
        content: Majored in Software Engineering
      - title: "Pre Engineering Diploma"
        school:
          name: "Budapest University of Technology and Economics"
          url: "https://www.bme.hu/"
        date: "2018 - 2019"
        # GPA: "3.7 out of 5.0"
        # featuredLink:
        #   enable: true
        #   name: "My academic record"
        #   url: "https://example.com"
      - title: "High School Diploma"
        school:
          name: "Pilote Highschool of Sousse"
          url: "https://www.facebook.com/Lycee.Pilote.de.Sousse.LPS"
        date: "2017"
        # GPA: "4.2 out of 5.0"
        # featuredLink:
        #   enable: true
        #   url: "https://example.com"

  # Achievements
  achievements:
    enable: true
    # title: "Custom Name"
    items:
      - title: Certified Kubernetes Application Developer
        content: The Linux Foundation
        # url: https://example.com
        image: /images/ckad.png
      - title: Fundamentals Of Deep Learning
        content: Nvidia
        image: /images/nvidia.png
      - title: Stipendium Hungaricum Scholarship
        content: Tempus Public Foundation
        # url: "https://github.com/gurusabarish/hugo-profile"
        image: /images/stipendium.png
  # projects
  projects:
    enable: false
    # title: "Custom Name"
    items:
      - title: Hugo Profile
        content: A highly customizable and mobile first Hugo template for personal portfolio and blog.
        image: /images/projects/profile.png
        featured:
          name: Demo
          link: https://hugo-profile.netlify.app
        badges:
          - "Hugo"
          - "Bootstrap"
          - "Javascript"
        links:
          - icon: fa fa-envelope
            url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
          - icon: fab fa-github
            url: https://github.com/gurusabarish/hugo-profile
          - icon: fab fa-twitter
            url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      - title: Image Converter
        content: A web app to convert image to pdf, png to jpg, png to jpg and png to webp without database using django.
        image: /images/projects/converter.jpg
        featured:
          name: Demo
          link: https://django-converter.herokuapp.com
        badges:
          - "Django"
          - "Bootstrap"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/converter

      - title: Hugo Profile V2
        content: A clean and simple Hugo template for personal portfolio and blog.
        image: /images/projects/profile2.jpg
        featured:
          name: Demo V2
          link: https://hugo-profile-2.netlify.app
        badges:
          - "Hugo"
          - "Bootstrap"
          - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/HugoProfileV2

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you!
    email: samer.bahri@thebahrimedia.com
    btnName: Mail me
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  # footer:
  #   recentPosts:
  #     path: "blogs"
  #     count: 3
  #     title: Recent Posts
  #     enable: true
  #     disableFeaturedImage: false
  #   socialNetworks:
  #     github: https://github.com
  #     linkedin: https://linkedin.com
  #     twitter: https://twitter.com
  #     instagram: https://instagram.com
  #     facebook: https://facebook.com

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
